env:
  browser: true
  node: true
extends:
  - 'eslint:recommended'
  - 'plugin:react/recommended'
  - 'airbnb'
parserOptions:
  ecmaFeatures:
    jsx: true
  sourceType: module
plugins:
  - react
rules:
  react/prop-types: 0
